name: Java Build and Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: ${{ github.workspace }}/target/*.jar
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: javatestgitlab
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
